"""
Google Trends collector for DebateTrader.

Proxies retail investor attention via Google search interest.
Uses the unofficial pytrends library (no API key required).

Design decisions:
  1. One ticker = one query (avoids cross-batch normalization entirely).
     For any dynamic stock pool of any size, each ticker's 0–100 series
     is self-contained: 100 = peak attention for that ticker in the period,
     0 = no searches.  The Sentiment Analyst uses within-ticker trends
     (spikes, week-over-week change) which require no cross-ticker scale.

  2. Search terms generated by Groq and cached.
     E.g. "BRK.B" (Berkshire Hathaway B shares) → "Berkshire Hathaway stock"
          "LLY"   (Eli Lilly)                   → "Eli Lilly stock"
          "AAPL"  (Apple)                        → "AAPL stock"
     Cache lives at data/cache/search_terms_cache.json (commit to git).
     Groq fallback: "<ticker> stock" if GROQ_API_KEY is absent or call fails.

  3. Weekly resolution (matches DebateTrader's weekly run cycle).

Output: data/sample/sentiment/google_trends_weekly.parquet

Schema (long format, one row = one ticker × one week):
  date              — week start (Monday), datetime64
  ticker            — canonical ticker symbol
  search_interest   — 0–100 relative search volume (Google Trends scale)
  search_term       — keyword sent to Google Trends
  geo               — search region ("US")

Downstream consumer: Sentiment Analyst agent
"""
from __future__ import annotations

import sys
import os
import json
import time
import logging

import pandas as pd
from pytrends.request import TrendReq

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
from src.data_collection.config import (
    TICKERS, SAMPLE_START, SAMPLE_END, SENTIMENT_DIR,
)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
CACHE_FILE       = os.path.join("data", "cache", "search_terms_cache.json")
GROQ_MODEL       = "llama-3.1-8b-instant"   # fast + cheap for this task
GEO              = "US"                      # US retail investor focus
RATE_LIMIT_SLEEP = 5.0                       # seconds between pytrends requests


# ---------------------------------------------------------------------------
# Search term cache & Groq generation
# ---------------------------------------------------------------------------

def _load_cache() -> dict[str, str]:
    if os.path.exists(CACHE_FILE):
        with open(CACHE_FILE, encoding="utf-8") as f:
            return json.load(f)
    return {}


def _save_cache(cache: dict[str, str]) -> None:
    os.makedirs(os.path.dirname(CACHE_FILE), exist_ok=True)
    with open(CACHE_FILE, "w", encoding="utf-8") as f:
        json.dump(cache, f, indent=2, ensure_ascii=False)


def _groq_suggest_term(ticker: str, company_name: str | None) -> str:
    """
    Call Groq LLM to get the single best Google search query for this ticker.
    Falls back to '<ticker> stock' if GROQ_API_KEY is missing or call fails.
    """
    api_key = os.environ.get("GROQ_API_KEY", "").strip()
    if not api_key:
        fallback = f"{ticker} stock"
        logger.warning(
            f"  No GROQ_API_KEY — using fallback term '{fallback}' for {ticker}."
        )
        return fallback

    try:
        from groq import Groq

        client  = Groq(api_key=api_key)
        company = f" ({company_name})" if company_name else ""
        prompt  = (
            f"What is the single best Google search query that retail stock investors "
            f"type when looking up {ticker}{company}?\n"
            f"Rules: return ONLY the search query, no explanation, 2–4 words max.\n"
            f"Examples:\n"
            f'  AAPL (Apple Inc.) → "AAPL stock"\n'
            f'  BRK.B (Berkshire Hathaway) → "Berkshire Hathaway stock"\n'
            f'  NVDA (Nvidia) → "Nvidia stock"\n'
            f"  {ticker}{company} → "
        )
        resp = client.chat.completions.create(
            model=GROQ_MODEL,
            messages=[{"role": "user", "content": prompt}],
            temperature=0,
            max_tokens=20,
        )
        term = resp.choices[0].message.content.strip().strip("\"'")
        logger.info(f"  Groq → '{term}'")
        return term

    except Exception as exc:
        fallback = f"{ticker} stock"
        logger.warning(f"  Groq error ({exc}). Using fallback '{fallback}'.")
        return fallback


def get_search_term(
    ticker: str,
    company_name: str | None = None,
    refresh: bool = False,
) -> str:
    """
    Return the Google Trends search term for a ticker.
    Reads from cache; calls Groq on first encounter (or when refresh=True).
    """
    cache = _load_cache()
    if ticker in cache and not refresh:
        logger.info(f"  Cache hit: {ticker} → '{cache[ticker]}'")
        return cache[ticker]

    term = _groq_suggest_term(ticker, company_name)
    cache[ticker] = term
    _save_cache(cache)
    return term


# ---------------------------------------------------------------------------
# pytrends fetch (one ticker at a time)
# ---------------------------------------------------------------------------

def _fetch_single(
    pt: TrendReq,
    ticker: str,
    search_term: str,
    timeframe: str,
    geo: str,
    max_retries: int = 3,
) -> pd.Series | None:
    """
    Fetch weekly interest_over_time for a single search term.
    Returns a Series indexed by date, or None on failure.

    Note: retries/backoff_factor are NOT passed to TrendReq because
    pytrends 4.9.x uses urllib3's deprecated `method_whitelist` argument
    (renamed `allowed_methods` in urllib3 ≥ 2.0). Manual retry is used
    instead to avoid that incompatibility.
    """
    for attempt in range(1, max_retries + 1):
        try:
            pt.build_payload([search_term], timeframe=timeframe, geo=geo, gprop="")
            df = pt.interest_over_time()
            break
        except Exception as exc:
            if attempt < max_retries:
                wait = 10 * attempt
                logger.warning(
                    f"  Attempt {attempt}/{max_retries} failed for {ticker}: {exc}. "
                    f"Retrying in {wait}s ..."
                )
                time.sleep(wait)
            else:
                logger.error(
                    f"  All {max_retries} attempts failed for {ticker}: {exc}"
                )
                return None

    if df is None or df.empty:
        logger.warning(f"  Empty response for {ticker} ('{search_term}').")
        return None

    if "isPartial" in df.columns:
        df = df.drop(columns=["isPartial"])

    series = df.iloc[:, 0].rename(ticker)
    return series


# ---------------------------------------------------------------------------
# Main collection function
# ---------------------------------------------------------------------------

def collect_google_trends(
    tickers: list[str] = TICKERS,
    start: str = SAMPLE_START,
    end:   str = SAMPLE_END,
    company_names: dict[str, str] | None = None,
    geo:   str = GEO,
    output_dir: str = SENTIMENT_DIR,
) -> pd.DataFrame:
    """
    Collect weekly Google Trends search interest for all tickers.

    Args:
        tickers       : list of canonical ticker symbols
        start / end   : date range as 'YYYY-MM-DD'
        company_names : optional {ticker: company_name} for better Groq prompts
        geo           : Google Trends geography (default 'US')
        output_dir    : where to write the parquet file

    Returns:
        Long-format DataFrame (one row per ticker × week).
    """
    company_names = company_names or {}
    timeframe     = f"{start} {end}"

    logger.info(
        f"[GoogleTrends] Collecting  {start} → {end}"
        f"  tickers={tickers}  geo={geo}"
    )
    os.makedirs(output_dir, exist_ok=True)

    # ------------------------------------------------------------------ step 1: search terms
    logger.info("[GoogleTrends] Resolving search terms (Groq + cache) ...")
    search_terms: dict[str, str] = {}
    for ticker in tickers:
        cname = company_names.get(ticker)
        search_terms[ticker] = get_search_term(ticker, company_name=cname)

    logger.info("[GoogleTrends] Search term mapping:")
    for ticker, term in search_terms.items():
        logger.info(f"  {ticker:8s} → '{term}'")

    # ------------------------------------------------------------------ step 2: fetch
    # Do NOT pass retries/backoff_factor: pytrends uses urllib3's deprecated
    # `method_whitelist` kwarg internally, which breaks on urllib3 >= 2.0.
    # Manual retry is implemented inside _fetch_single instead.
    pt = TrendReq(hl="en-US", tz=360, timeout=(10, 25))

    records: list[dict] = []
    for i, ticker in enumerate(tickers):
        term = search_terms[ticker]
        logger.info(f"  [{i + 1}/{len(tickers)}] {ticker} ('{term}') ...")

        series = _fetch_single(pt, ticker, term, timeframe, geo)

        if series is not None:
            for date, value in series.items():
                records.append({
                    "date":            pd.Timestamp(date).normalize(),
                    "ticker":          ticker,
                    "search_interest": round(float(value), 2),
                    "search_term":     term,
                    "geo":             geo,
                })
            logger.info(
                f"    {len(series)} weeks  "
                f"avg={series.mean():.1f}  peak={series.max():.1f}"
            )
        else:
            logger.warning(f"  No data for {ticker} — excluded from output.")

        if i < len(tickers) - 1:
            logger.info(f"    Waiting {RATE_LIMIT_SLEEP}s ...")
            time.sleep(RATE_LIMIT_SLEEP)

    # ------------------------------------------------------------------ step 3: save
    if not records:
        logger.error("[GoogleTrends] No data collected.")
        return pd.DataFrame()

    df_long = (
        pd.DataFrame(records)
        .sort_values(["ticker", "date"])
        .reset_index(drop=True)
    )

    out_path = os.path.join(output_dir, "google_trends_weekly.parquet")
    df_long.to_parquet(out_path, index=False, engine="pyarrow")
    logger.info(
        f"[GoogleTrends] Saved → {out_path}  ({len(df_long)} rows)"
    )

    # Summary
    logger.info("[GoogleTrends] Summary:")
    for ticker, grp in df_long.groupby("ticker"):
        avg  = grp["search_interest"].mean()
        peak = grp["search_interest"].max()
        logger.info(f"  {ticker:8s}  avg={avg:.1f}  peak={peak:.1f}")

    return df_long


def run(
    tickers: list[str] = TICKERS,
    start:   str = SAMPLE_START,
    end:     str = SAMPLE_END,
    company_names: dict[str, str] | None = None,
) -> None:
    collect_google_trends(tickers, start, end, company_names=company_names)
    logger.info("[GoogleTrends] Done.")


if __name__ == "__main__":
    from dotenv import load_dotenv
    load_dotenv()
    run()
